# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
trust-domain: application-services
task-priority: highest

taskgraph:
  register: app_services_taskgraph:register
  repositories:
    appservices:
      name: "Application Services"
  cached-task-prefix: project.application-services
  decision-parameters: 'app_services_taskgraph:get_decision_parameters'

workers:
  aliases:
    b-linux:
      provisioner: 'app-services-{level}'
      implementation: docker-worker
      os: linux
      worker-type: 'b-linux'
    images:
      provisioner: 'app-services-{level}'
      implementation: docker-worker
      os: linux
      worker-type: 'images'
    dep-signing:
      provisioner: scriptworker-k8s
      implementation: scriptworker-signing
      os: scriptworker
      worker-type: appservices-t-signing
    signing:
      provisioner: scriptworker-k8s
      implementation: scriptworker-signing
      os: scriptworker
      worker-type:
        by-level:
          "3": appservices-3-signing
          default: appservices-t-signing
    dep-beetmover:
      provisioner: scriptworker-k8s
      implementation: scriptworker-beetmover
      os: scriptworker
      worker-type: appservices-1-beetmover
    beetmover:
      provisioner: scriptworker-k8s
      implementation: scriptworker-beetmover
      os: scriptworker
      worker-type: 'appservices-{level}-beetmover'

scriptworker:
  scope-prefix: project:mozilla:application-services:releng
