# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
trust-domain: app-services
task-priority: highest

taskgraph:
  register: app_services_taskgraph:register
  repositories:
    mobile:
      name: "Application Services"
  cached-task-prefix: project.mozilla.app-services
  decision-parameters: 'app_services_taskgraph:get_decision_parameters'

workers:
  aliases:
    b-linux:
      provisioner: aws-provisioner-v1
      implementation: docker-worker
      os: linux
      worker-type: 'app-services-{level}-b-linux'
    images:
      provisioner: aws-provisioner-v1
      implementation: docker-worker
      os: linux
      worker-type: 'mobile-{level}-images'

scriptworker:
  scope-prefix: project:mozilla:application-services:releng
